### ISSUE TITLE
INSERIMENTO CATTEDRE SUPPLENZA E INSERIMENTO VOTO

### ISSUE THREAD

**Issue by nicholas20220** [scaforchio/LAMPSchool#102]
Salve buonasera,  vorrei fare due domande
1)quando devo mettere una cattedra per le supplenze per molto tempo devo inserire la materia di insegnamento in quanto il docente supplente per molto tempo deve mettere i voti. Come posso fare ad inserirlo.
2)Si potrebbero inserire più voti nei giorni. grazie attendo risposta

**Comment by manuelbarberi** [comment]
Ti consiglio giuaschool... è una rivisitazione di lampschool
