### ISSUE TITLE
PROPOSTA

### ISSUE THREAD

**Issue by nicholas20220** [scaforchio/LAMPSchool#103]
Buonasera ,
sono il RAPPRESENTANTE LEGALE (Presidente) Dell' Associazione Nazionale Programmatori Bitrix24,
Le volevo fare la proposta di unirsi lei con il suo team al mio nucleo (tutto a carico mio in quanto rappresentante legale). 

In attesa di un suo cortese riscontro le auguro una buona serata.
Distinti Saluti
Presidenza Associazione Nazionale Programmatori Bitrix24

**Comment by manuelbarberi** [comment]
Lei è rappresentate legale dell'associazione?

**Comment by nicholas20220** [comment]
Buonasera, si sono il rappresentante legale dell'associazione, per informazioni se vuole le posso lasciare una mia mail.
Saluti
N.C
