### ISSUE TITLE
LAMPSchool non funziona in HTTPS!

### ISSUE THREAD

**Issue by mcc-macca** [scaforchio/LAMPSchool#106]
Ho installato LAMPSchool su altervista.
L'accesso me lo fa fare sono se sono in HTTP, mentre in HTTPS non funziona.
Ho provato a installarlo in HTTPS, ma stessa roba. non funziona e da' errore nella sezione admin durante l'HTTP request nel file lampschool.json

**Comment by vittodevit** [comment]
Salve! AlterVista è una piattaforma nota per causare problemi con LampSchool. Consigliamo l'hosting su Aruba o su una VPS.

**Comment by robertopadovesi** [comment]
@mcc-macca Buongiorno! Avrei bisogno di parlarti, in merito a questa richiesta e anche in merito a un progetto. Posso parlarti in privato? Mi scrivi alla mia mail: [padovesi.roberto@gmail.com](mailto:padovesi.roberto@gmail.com)? Grazie!
