### ISSUE TITLE
Messaggio di errore

### ISSUE THREAD

**Issue by alessandroandrei** [scaforchio/LAMPSchool#107]
Salve, una volta completata la procedura di installazione, quando arrivo alla schermata di login in cui inserire le credenziali da admin vengo reindirizzato a questo messaggio di errore: 

Attenzione! Errore di sistema.
Contattare il referente per il registro!

******
logincheck.php
03-25|12:04:10§
Errore: Unknown column 'oidc_authmode' in 'field list'
Query: SELECT oidc_authmode FROM tbl_utenti WHERE userid='admin' AND oidc_authmode = 'x'

come posso risolvere? grazie

**Comment by mcc-macca** [comment]
1. Apri phpMyAdmin
2. Vai a selezionare il database, poi la tabella `tbl_utenti`
3. Aggiungi il valore `x` nella colonna `oidc_authmode`
4. Salva tutto e poi fai il refresh della pagina e ri-esegui il login

------

Oppure cancelli la colonna `oidc_authmode`

**Comment by vittodevit** [comment]
Il bug è nello script di installazione/aggiornamento che crea una struttura del database sbagliata e verrà risolto nella prossima release.

La soluzione proposta da @mcc-macca è sbagliata siccome il valore di default deve essere `d`, se impostata su `x` con OIDC disabilitato da parametri si disabiliterà l'accesso regolare con user e pass per tutti gli utenti registrati. Cancellare la colonna nemmeno aiuterà siccome a OIDC attivato questo renderà il registro inutilizzabile.

----------------------
@alessandroandrei come risolvere:
Per risolvere pre-aggiornamento basta creare la colonna `oidc_authmode` (se manca) e impostarla interamente  a `d`.

**Comment by vittodevit** [comment]
Sistemato in #108
