### ISSUE TITLE
Problema aggiornamento

### ISSUE THREAD

**Issue by mimmomarino** [scaforchio/LAMPSchool#120]
Buonasera,
Di recente ho installato il nuovo aggiornamento, ma, al momento del login, il sito mi indirizza ad una pagina non funzionante.

Spero possiate risolvere il problema il più presto possibile.

**Comment by mimmomarino** [comment]
Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /membri/[nomedominio]/Registro/lib/admqtt.php on line 3

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:') in /membri/[nomedominio]/Registro/lib/admqtt.php on line 3

Mi spunta questo errore

**Comment by vittodevit** [comment]
Salve, non ha seguito correttamente la procedura di installazione.
https://github.com/scaforchio/LAMPSchool/blob/master/INSTALL.md#installazione-di-lampschool indica dopo il caricamento dei file nel server:
> Successivamente, bisogna scaricare le dipendenze composer. Per fare questo, una volta        
> installato composer sul server (vedi [Installazione Composer](https://getcomposer.org/download/)) bisogna lanciare nella cartella root il comando composer install.

Si assicuri anche che la versione di PHP sia la 7.4   
Se ha problemi ad eseguire composer o si trova in un ambiente di hosting shared, a breve pubblicheremo uno zip che include già tutte le dipendenze.

**Comment by manuelbarberi** [comment]
@vittodevit dove posso trovare questo zip?

**Comment by manuelbarberi** [comment]
@scaforchio dove posso trovare il file zip con tutte le dipendenze necessarie?

**Comment by vittodevit** [comment]
Lo può realizzare in autonomia sulla propria macchina clonando la repository, eseguendo composer install e ri-zippando la cartella dopo il comando per caricarla sulla piattaforma di hosting shared.
