### ISSUE TITLE
Problema Installazione ed Accesso con ALTERVISTA

### ISSUE THREAD

**Issue by manuelbarberi** [scaforchio/LAMPSchool#135]
Dopo installazione di Lampschool la pagina di accesso non viene visualizzata correttamente e l'accesso non è possibile da effettuare poichè il server restituisce il seguente codice di errore: 

Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /membri/[nomedominio]/Registro/lib/admqtt.php on line 3

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:') in /membri/[nomedominio]/Registro/lib/admqtt.php on line 3

@zerai @valerio-bozzolan @scaforchio @GabrielTavernini @vittodevit

**Comment by valerio-bozzolan** [comment]
Ciao Manuel,

Non sono un contributore di questo software ma ho notato che la guida dice di eseguire Composer prima. Probabilmente non è stato fatto e questo spiega il tuo errore.

Invito a ri-leggere quella parte e in generale questo documento che spiega molte cose in 10 minuti:

https://github.com/scaforchio/LAMPSchool/blob/master/INSTALL.md#note-di-installazione-di-lampschool

Segno come chiuso sperando di aver chiarito, anche perchè questo non è probabilmente un problema risolvibile dagli sviluppatori di LAMPSchool, ma da un tecnico (che invitiamo a cercare nella vostra città - competenze necessarie: PHP - non farete fatica a trovare questo supporto, è una competenza tecnica relativamente comune rispetto ad altre).
