### ISSUE TITLE
Aiuto problema installazione versione 2023

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#136]
Buongiorno, qualcuno mi potrebbe aiutare con l'installazione del registro Lampschool sull'hosting Altervista dal momento che sto riscontrando diverse problematiche?Grazie. Aspetto con urgenza una risposta . @scaforchio @valerio-bozzolan @GabrielTavernini

**Comment by vittodevit** [comment]
Altervista non è una piattaforma supportata per l'installazione di LAMPSchool

**Comment by tommasiangelo01** [comment]
Ci sarebbe una piattaforma alternativa non a pagamento?

Il Gio 21 Dic 2023, 12:55 Vittorio Lo Mele ***@***.***> ha
scritto:
