### ISSUE TITLE
problema installazione urgente

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#137]
![unnamed](https://github.com/scaforchio/LAMPSchool/assets/93207960/7cbb7aaf-c415-4c40-91e9-b91d2565dfda)
allego foto degli errori @valerio-bozzolan @scaforchio @GabrielTavernini @zerai

**Comment by gmontalbano5ct** [comment]
@valerio-bozzolan

**Comment by gmontalbano5ct** [comment]
@scaforchio

**Comment by gmontalbano5ct** [comment]
@zerai @GabrielTavernini

**Comment by vittodevit** [comment]
Buongiorno, penso che sia più utile leggere le istruzioni di installazione che taggare ogni mantainer della repo...

> Successivamente, bisogna scaricare le dipendenze composer. Per fare questo, una volta installato composer sul server (vedi [Installazione Composer](https://getcomposer.org/download/)) bisogna lanciare nella cartella root il comando composer install.

Vi siete persi questo passaggio, in futuro sarà aggiunta la possibilità di scaricare un pacchetto già pronto.

**Comment by gmontalbano5ct** [comment]
@vittodevit scusa ma quale cartella devo lanciare per l'installazione?
