### ISSUE TITLE
Errore Accesso

### ISSUE THREAD

**Issue by Karimio29** [scaforchio/LAMPSchool#138]
Nel momento in cui effettuo l'accesso al sistema, mi compare il seguente errore (premetto che utilizzo altervista):

**Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /membri/[nomedomino]/LAMPSchool-master/LAMPSchool-master/lib/admqtt.php on line 3

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:') in /membri/[nomedomino]/LAMPSchool-master/LAMPSchool-master/lib/admqtt.php on line 3**

Qualcuno potrebbe aiutarmi? grazie mille

**Comment by gmontalbano5ct** [comment]
@Karimio29 ho il tuo stesso identico problema hai risolto?

**Comment by Karimio29** [comment]
Sfortunatamente no

**Comment by vittodevit** [comment]
Vedere #137, inoltre Altervista non è una piattaforma supportata da LAMPSchool siccome è ormai appurato il fatto che dia problemi.

**Comment by gmontalbano5ct** [comment]
@Karimio29 salve lei è in grado di scaricare e far funzionare questo registro?
