### ISSUE TITLE
Implementazioni versione 2023.4

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#139]
Buongiorno sarebbe possibile sapere quale sono le implementazioni presenti nella versione 2023.4 dal momento che io sono rimasto alla versione 2019 ? 

Sarebbe possibile avere una guida pdf per docente,staff ,amministratore , genitore e alunno?Grazie

**Comment by vittodevit** [comment]
Può tranquillamente leggere in autonomia il changelog
