### ISSUE TITLE
il problema si ripete anche con altro hosting 

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#140]
Buongiorno ,ho visto che il problema dell'installazione si ripete anche con un altro hosting validissimo ,ossia "x10hosting" , come mai?Credo che la procedura di installazione da voi indicata sia impossibile /troppo complicata per tutti ,come già notato dalle continue richieste di aiuto .Mi sento di dire che è più facile l'installazione di giuaschool ,quando prima era il processo inverso ,come mai?

**Comment by chri2021** [comment]
Ciao mi puoi contattare tramite email: christianfortunato41@gmail.com

**Comment by vittodevit** [comment]
La procedura di installazione non è impossibile per tutti... 
<img width="1453" alt="image" src="https://github.com/scaforchio/LAMPSchool/assets/58268988/c0b6e1be-da35-45c6-9e27-b9ce8dd26ae3">
quella in foto mi sembra un installazione funzionante!

In caso di difficoltà si può sempre consultare la guida ufficiale nel README oppure chiedere informazioni sul forum della ILS: 
https://forum.linux.it/t/domande-su-lampschool-e-giuia-school-registri-elettronici-liberi/264/17
