### ISSUE TITLE
Aiuto istallazione lampschool

### ISSUE THREAD

**Issue by chri2021** [scaforchio/LAMPSchool#141]
Salve qualcuno mi può aiutare a istallare lampschool. Mi potete contattare sull'email: christianfortunato41@gmail.com
Cordiali saluti

**Comment by vittodevit** [comment]
Per le richieste di aiuto gentilmente non negli issues (e neanche alle e-mails dei mantainer e telegram personali, grazie) ma sul forum della ILS https://forum.linux.it/t/domande-su-lampschool-e-giuia-school-registri-elettronici-liberi/264/17

**Comment by robertopadovesi** [comment]
@chri2021 Buongiorno! Avrei bisogno di parlarti, in merito a questa richiesta e anche in merito a un progetto. Posso parlarti in privato? Mi scrivi alla mia mail: [padovesi.roberto@gmail.com](mailto:padovesi.roberto@gmail.com)? Grazie!
