### ISSUE TITLE
Problema dopo l'installazione

### ISSUE THREAD

**Issue by Davide031** [scaforchio/LAMPSchool#142]
Buonasera una volta che io finisco l'installazione ed entro con le credenziali admin esce il seguente errore
Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /membri/istitutoscientificogalil/Re2024/lib/admqtt.php on line 3

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:') in /membri/istitutoscientificogalil/Re2024/lib/admqtt.php on line 3
ho provato con tutte le versioni php che offre altervista ma nulla potrei avere un aiuto
Grazie.

**Comment by vittodevit** [comment]
Altervista NON è una piattaforma supportata, come già indicato nel manuale di installazione INSTALL.md

<img width="1048" alt="image" src="https://github.com/scaforchio/LAMPSchool/assets/58268988/6c61201a-d906-41b1-9fee-3ea402d83b01">
