### ISSUE TITLE
errore dopo installazione- aiuto urgente

### ISSUE THREAD

**Issue by NowCmd** [scaforchio/LAMPSchool#146]
dopo aver copiato i file, provo ad aprire il link per installare il programma ma viene mostrato questo errore:

Warning: require(../vendor/autoload.php): failed to open stream: No such file or directory in /membri/classescuola/lib/funzioni.php on line 29

Fatal error: require(): Failed opening required '../vendor/autoload.php' (include_path='.:') in /membri/classescuola/lib/funzioni.php on line 29
grazie.

**Comment by vittodevit** [comment]
L'installazione è stata fatta male, bisogna eseguire il passaggio di composer!
Vedere il manuale INSTALL.md

**Comment by NowCmd** [comment]
> L'installazione è stata fatta male, bisogna eseguire il passaggio di composer! Vedere il manuale INSTALL.md

come posso installare composer su altervista?
