### ISSUE TITLE
Installazione 2024 - Errore typo in file sql

### ISSUE THREAD

**Issue by Si-dvp** [scaforchio/LAMPSchool#160]
Segnalo un errore e la soluzione che ho utilizzato io per risolverlo, sperando sia corretta...
Nel processo di installazione dell'ultima versione (2024) compare una riga di errore che fa riferimento alla quelli: 
```
ALTER TABLE `tbl_alunni`
  ADD `censito` VARCHAR(5) NOT NULL DEFAULT '0' after `autorizzazioni`,
  ADD `idgrupporitardo` INT NOT NULL DEFAULT '1' after `censito`,
  ADD `telproprio` VARCHAR(20) NOT NULL DEFAULT '' after `idgrupporitardo`,
  ADD `mailpropria` VARCHAR(100) NOT NULL DEFAULT '' after `telproprio`,
  ADD `totpgiustass` VARCHAR(120) NULL DEFAULT NULL AFTER `mailpropria`
  ADD `liberatoria` TINYINT NOT NULL DEFAULT 0 AFTER `totpgiustass`;
```

Nella parte di testo qui riportata (presa dal file 2023.6.sql, cartella release, ma identica nel file 2024.sql) manca una virgola alla fine della penultima riga, che quindi dovrebbe essere corretta -credo- in questo modo:
```
ALTER TABLE `tbl_alunni`
  ADD `censito` VARCHAR(5) NOT NULL DEFAULT '0' after `autorizzazioni`,
  ADD `idgrupporitardo` INT NOT NULL DEFAULT '1' after `censito`,
  ADD `telproprio` VARCHAR(20) NOT NULL DEFAULT '' after `idgrupporitardo`,
  ADD `mailpropria` VARCHAR(100) NOT NULL DEFAULT '' after `telproprio`,
  ADD `totpgiustass` VARCHAR(120) NULL DEFAULT NULL AFTER `mailpropria`,
  ADD `liberatoria` TINYINT NOT NULL DEFAULT 0 AFTER `totpgiustass`;
```

Solo per conferma, chiedo se è corretto che dopo 'totpgiustass' il codice sia
``` 
ADD `totpgiustass` VARCHAR(120) NULL DEFAULT NULL AFTER `mailpropria`,
```

o se invece di NULL la riga deve essere NOT NULL, in questo modo:
```
  ADD `totpgiustass` VARCHAR(120) NOT NULL DEFAULT NULL AFTER `mailpropria`,
```

Grazie

**Comment by vittodevit** [comment]
Ciao! L'issue è stato fixato dagli ultimi due commit fatti urgentemente direttamente nel master. 

Per quanto riguarda il field `totpgiustass` è giusto sia NULL all'inizio perchè un genitore può non aver ancora ricevuto un codice TOTP per giustificare le assenze del figlio.
