### ISSUE TITLE
Due nuovi video di documentazione su YouTube

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#37]
Sarebbe utile creare almeno due nuovi video di documentazione su YouTube in CC BY per: 

1. [x] prenotazione dei colloqui pomeridiani da parte dei genitori (nuova funzione già implementata)
2. [x] inserimento dei link meet per i docenti in vista delle lezioni a distanza (nuova funzione già implementata)

----

Edited. messaggio originale:

Buongiorno,sarebbe bellissimo e allo stesso tempo utile se ci fosse un nuovo canale youtube di LAMPSCHOOL sempre aggiornato .É possibile

**Comment by valerio-bozzolan** [comment]
Grazie @tommasiangelo01 

Per iniziare sarebbe utile appuntare un primo piccolo elenco di 2-3 funzionalità quotidiane già coperte in LAMPSchool per farci piccoli video tutorial molto brevi ma utili sopra.

Vi vengono in mente già 2-3 temi? Tipo "Come recuperarae la password di LAMPSchool". etc.

Grazie buon week-end

**Comment by tommasiangelo01** [comment]
Ottimo

Il giorno dom 31 ott 2021 alle ore 11:19 Valerio Bozzolan <
***@***.***> ha scritto:

**Comment by tommasiangelo01** [comment]
un altro tema potrebbe essere la prenotazione dei colloqui pomeridiani da parte dei genitori (nuova funzione  già implementata )

un altro tema potrebbe essere l'inserimento dei link meet per i docenti in vista delle lezioni a distanza (nuova funzione già implementata)

**Comment by tommasiangelo01** [comment]
Secondo me con il materiale nuovo che c'è è già possibile dar vita ad un nuovo canale LAMPSCHOOL

**Comment by valerio-bozzolan** [comment]
Riapro questa issue siccome mi pare che non è stato ancora prodotto nessun video fra quelli richiesti.

**Comment by tommasiangelo01** [comment]
Sarebbe possibile mandarci anche un messaggio non appena pubblicate il nuovo canale Youtube dedicato a Lampschool in modo da sollecitare tutto il nostro personale ad iscriversi?Grazie

**Comment by sempliciniluigi89** [comment]
Stavo pensando che nel nuovo canale youtube che sarà creato sarebbe possibile integrare anche il tutorial con istruzioni sull'accesso al registro con lo SPID che verrà implementato in questo mese
