### ISSUE TITLE
Richiesta colorazioni voti e legenda voti nel file  visvaltut.php ed il tabellone

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#38]
Buongiorno, ho avuto questa idea che mi sembra a dir poco favolosa: Sarebbe possibile riprodurre in base al voto questi colori in modo da risaltare subito all'occhio per capire di che voto si tratta (se sufficiente o insufficiente) sia per quanto riguarda la visuale nell'area "voti" dei genitori che il "tabellone riepilogo lezione dei docenti"? Vi allego due PDF di esempio, uno per quanto riguarda il lato genitore, l'altro per quanto riguarda il lato docente. Un esempio:

![Screenshot voti colorati](https://user-images.githubusercontent.com/6052909/139587293-0d5ba5e4-8c8b-4f4e-833e-7e986921abb5.png)

**Comment by vittodevit** [comment]
In lavorazione sulla pull request #41

**Comment by tommasiangelo01** [comment]
Sembra già perfetto

Il giorno dom 31 ott 2021 alle ore 13:31 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by vittodevit** [comment]
![image](https://user-images.githubusercontent.com/58268988/139585175-61311891-6876-41ed-822f-ba12751193c8.png)
Ecco come appare in tabellone.

**Comment by tommasiangelo01** [comment]
Bellissimo,una sola richiesta:si potrebbe togliere la sottolineatura dei
nomi degli studenti e delle date ?

Il giorno dom 31 ott 2021 alle ore 14:13 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by vittodevit** [comment]
> Bellissimo,una sola richiesta:si potrebbe togliere la sottolineatura dei nomi degli studenti e delle date ? 

Suggerisco di no, sono link, e creerebbe parecchia confusione se qualcuno li deve cliccare.

**Comment by tommasiangelo01** [comment]
Va benissimo,entro più o meno quando dovrebbe essere attiva la funzione
della colorazione voti ?

Il giorno dom 31 ott 2021 alle ore 14:27 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by valerio-bozzolan** [comment]
Grazie! Ho aggiornato il primo commento per togliere il link all'allegato e allegare invece un piccolo screenshot.

**Comment by tommasiangelo01** [comment]
Scusi se la disturbo nuovamente, ma dal punto di vista di grafica la colorazione dell'intera cella fa la sua netta differenza ,vedendo lo screen che ha allegato Valerio-Bozzolan si nota tanto la differenza , dunque per me è preferibile lasciare la colorazione per l'intera cella.Anche perchè è quasi impossibile mettere tre valutazioni di tipo diverse

**Comment by vittodevit** [comment]
> Scusi se la disturbo nuovamente, ma dal punto di vista di grafica la colorazione dell'intera cella fa la sua netta differenza ,vedendo lo screen che ha allegato Valerio-Bozzolan si nota tanto la differenza , dunque per me è preferibile lasciare la colorazione per l'intera cella.Anche perchè è quasi impossibile mettere tre valutazioni di tipo diverse

Il problema è anche nel modo in cui è fatto il ciclo che stampa la tabella, quindi l'implementazione più sensata è quella di creare "quadratini" diversi per ogni valutazione.

**Comment by tommasiangelo01** [comment]
va bene ,attendo il rilascio di questa pull request.Grazie mille lo stesso
, davvero!Noto una disponibilità continua e una predisposizione nel rendere
le nostre idee realtà ,grazie.

Il giorno dom 31 ott 2021 alle ore 15:27 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by vittodevit** [comment]
Aspettiamo il merge!

**Comment by tommasiangelo01** [comment]
Dunque dice che domani potrebbe già essere attiva la funzione?

**Comment by tommasiangelo01** [comment]
Entro domani dovrebbe essere già attiva giusto?

Il giorno dom 31 ott 2021 alle ore 15:39 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by vittodevit** [comment]
Dipende da quando viene fatto il merge.

**Comment by valerio-bozzolan** [comment]
Invito a testare questa funzionalità nell'ultima versione disponibile.

Grazie @vittodevit per il lavoro svolto! Invito ad aggiungere ulteriori commenti a riguardo qui sotto anche se chiuso.

**Comment by tommasiangelo01** [comment]
Buongiorno ,una piccola richiesta dal punto di vista grafico /estetico:sarebbe possibile rendere  tutti i voti sia per lato docente che genitore  in grassetto e di colore bianco o sarebbe un problema per la stampa ?Chiedo questo perché non si intona molto bene il colore nero del voto con la cella verde .Grazie mille
