### ISSUE TITLE
Bypass protezione da origini richiesta non autorizzate per impedire accessi dall'esterno (login/ele_ges.php)

### ISSUE THREAD

**Issue by mrBackSlash-it** [scaforchio/LAMPSchool#4]
**PROBLEMA**
È possibile bypassare la protezione da origini non autorizzate presente nel file `login/ele_ges.php` a partire dalla riga `25`.

**CODICE (login/ele_ges.php a partire da riga 25 fino a riga 37)**
```
$urlorigine = $_SERVER['HTTP_REFERER'];
if (isset($_SERVER['HTTPS']))
{
    $urlattuale = 'http' . ($_SERVER['HTTPS'] == 'on' ? 's' : '') . '://' . $_SERVER['SERVER_NAME'];
} else
{
    $urlattuale = 'http://' . $_SERVER['SERVER_NAME'];
}

if ($urlattuale == substr($urlorigine, 0, strlen($urlattuale)))
{
    $origineok = true;
}
```

**SPIEGAZIONE**
L'url dell'origine della richiesta, memorizzato nella variabile `$urlorigine` è ottenuto dal parametro `HTTP_REFERER`, mentre il contenuto della variabile `$urlattuale` è ottenuto dal parametro `SERVER_NAME`.
La variabile `$urlattuale` dovrebbe contenere l'url corretto del server quindi l'origine fidata delle richieste.
Il problema risiede nel fatto che il controllo per la legittimità della richiesta non è altro che un substring tra le due variabili, ed `$urlorigine` può essere controllato dallo _user-agent_ (client che effettua la richiesta). 
L'altra variabile (`$urlattuale`), è prevedibile in base a come è stato configurato il server (in caso del server test di PHP è l'ip a cui è stato bindato).
Potendo controllare uno dei due parametri e modificarlo liberamente in base alla previsione dell'altro si può falsare la legittimità della richiesta rendendo di fatto il controllo totalmente inutile.

**ESEMPIO ATTACCO CON RELATIVI SNIPPET DI CODICE**
L'attaccante crea un server NGINX sul dominio `example.com` e nella configurazione imposta che ogni richiesta verso `example.com/lampschool/*` va passata tramite proxy_pass al server originale che è bindato all'indirizzo IP `1.2.3.4`.
_CODICE CONFIGURAZIONE (Solo location block)_
```
location ^~ /lampschool/ {
   proxy_pass http://1.2.3.4:80;
   proxy_redirect http:// https://;
   proxy_http_version 1.1;
   proxy_set_header Host $host;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection $connection_upgrade;
}

```
In questo modo gli utenti che visitano `example.com/lampschool` avranno una copia esatta e funzionante del registro hostato su `1.2.3.4`, ma appena effettuano il login, il pezzo di codice effettua il controllo sull'origine fallisce dato che `$urlorigine` è uguale a `https://example.com/lampschool/logincheck.php` mentre `$urlattuale` è uguale a `http://1.2.3.4`.
Basta però fare una piccola modifica alla configurazione di NGINX per rendere questa protezione inutile.
Inserendo dopo `proxy _http_version.... ` il pezzo di config `proxy_set_header Referer "http://1.2.3.4/aaaaaaarandomdata";`, NGINX sovrascriverà tutti gli header `Referer` inviati dal browser con quella stringa di testo. 
La variabile `$urlorigine`, prendendo i dati da `HTTP_REFERER` non fa altro che memorizzare dentro se stessa il valore di quell'header appena modificato da NGINX. Di conseguenza, prevedendo il valore di `$urlattuale`, è possibile creare una stringa di testo che farà tornare dalla substringa `true`. Ciò marchierà la richiesta come legittima e lo script proseguirà con la visualizzazione dei dati e le sue operazioni.

Edit: corretto codice, mancava una riga

**Comment by scaforchio** [comment]
L'analisi è ben fatta ma non tiene conto del fatto che la sottostringa esaminata è quella che parte dalla posizione 0.
