### ISSUE TITLE
Problema lentezza AlterVista

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#43]
buona sera volevo capire il perché della lentezza per esempio ogni tanto succede che mentre un mio docente firma la propria lezione esempio va nella propria cattedra e gli si blocca oppure va sulla ora di lezione e si blocca e deve quindi tornare indietro e ripetere il passaggio. perché? grazie in anticipo.

N.d.r è in uso AlterVista

**Comment by vittodevit** [comment]
> buona sera volevo capire il perché della lentezza per esempio ogni tanto succede che mentre un mio docente firma la propria lezione esempio va nella propria cattedra e gli si blocca oppure va sulla ora di lezione e si blocca e deve quindi tornare indietro e ripetere il passaggio. perché? grazie in anticipo.

Questo molto probabilmente non dipende da LAMPSchool direttamente. Riesci a dare qualche info in più sulla configurazione e caratteristiche del server?

**Comment by gmontalbano5ct** [comment]
No purtroppo no

**Comment by vittodevit** [comment]
> No purtroppo no

Allora non so veramente come aiutarti. Riesci almeno a dirmi dove hosti? 

Se hosti su WebHosting shared Aruba per esempio chiami la loro assistenza.

**Comment by gmontalbano5ct** [comment]
Con altervista

**Comment by vittodevit** [comment]
> Con altervista

Altervista è stato provato più volte e dichiarato come non supportato, solo che questo avviso non è presente nel README.md

@valerio-bozzolan aggiungiamo?

**Comment by gmontalbano5ct** [comment]
Funziona solo che con il computer è più lento

**Comment by vittodevit** [comment]
> Funziona solo che con il computer è più lento

Si, può funzionare, solo che Altervista non è mai stato un host supportato ed è noto per causare problemi.

**Comment by valerio-bozzolan** [comment]
AlterVista è un hosting condiviso gratuito e non fornisce alcun requisito di performance. Sullo stesso server per rientrare nei costi fanno girare centinaia se non migliaia di altri siti web estranei.

Sarebbe meglio almeno una VPS per garantire specifiche contrattuali chiare.

Volevo chiedere a @gmontalbano5ct se posso attivarmi per farvi girare un preventivo per una migrazione del genere, eventualmente integrando altre lavorazioni, come il login per SPID o altre funzionalitá di cui avete bisogno subito.

Grazie gentilissimi

**Comment by gmontalbano5ct** [comment]
Ok per me va bene

**Comment by valerio-bozzolan** [comment]
@gmontalbano5ct mi potrebbe far scrivere qui dal vostro indirizzo istituzionale?

direttore@linux.it

Grazie mille gentilissimi

**Comment by valerio-bozzolan** [comment]
@gmontalbano5ct Avrei bisogno di sapere in privato l'indirizzo della vostra installazione, per capire il da farsi. Mi può scrivere qui in privato:

direttore@linux.it

(Non ho ricevuto comunicazioni)
