### ISSUE TITLE
LAMPSCHOOL BOOTSTRAP 

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#44]
Buonasera ,girando sulla rete ho visto sul vecchio forum di LAMPSCHOOL alcune immagini che vi allego ,dunque queste sono le immagini di una nuova grafica di LAMPSCHOOL ideata  nel 2014 con bootstrap ,pensata ma mai distribuita o attivata ,sarebbe possibile secondo voi fare ancora qualcosa per LAMPSCHOOL con bootstrap?

Vi allego i file riportanti le modifiche fatte e mai rese pubbliche o comunque attivate 

usp=sharinghttps://drive.google.com/file/d/1iUqtx-9ebuTOR5nMjRFRrjZbr5UsfdQ4/view?usp=sharinghttps://drive.google.com/file/d/1jlJNKKwyFwsvIhyBEorHFDSJDHIYK578/view?usp=sharinghttps://drive.google.com/file/d/1AyYuUBzAxBC4-0q3gETrjq7fBHsxPYaY/view?usp=sharinghttps://drive.google.com/file/d/1f6Rbq-KksilUnRisYQx-jBQV4bvboG1C/view?usp=sharing

**Comment by vittodevit** [comment]
Nel 2014 LAMPSchool era in uno stato molto più embrionale e meno complesso, quindi l'implementazione risultava infinitamente più facile, anche se sarebbe un'ottima idea renderlo responsive.

Purtroppo il tempo a disposizione che abbiamo per questo tipo di interventi è quasi zero e servirebbero finanziamenti ed altri sviluppatori.

**Comment by tommasiangelo01** [comment]
Capisco e vi ringrazio immensamente lo stesso

Il giorno lun 1 nov 2021 alle ore 10:46 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by valerio-bozzolan** [comment]
Questa è una buona idea. Integro in #12 e chiudiamo qui, proseguendo là. Grazie @tommasiangelo01

**Comment by tommasiangelo01** [comment]
Grazie mille ,mi potrebbe solo spiegare la frase "proseguendo là" in che
senso?

Il giorno lun 1 nov 2021 alle ore 11:53 Valerio Bozzolan <
***@***.***> ha scritto:

**Comment by valerio-bozzolan** [comment]
Intendo, proseguendo qui:

https://github.com/scaforchio/LAMPSchool/issues/12

Un caro saluto
