### ISSUE TITLE
Problema accesso su lampschol scaforchio app studenti

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#45]
Ecco cosa mi appare dopo aver inserito i dati corretti
#
![IMG_20211101_144932](https://user-images.githubusercontent.com/93207960/139682179-756480d6-3fe8-414b-8585-2a303200ad73.jpg)

**Comment by vittodevit** [comment]
L'app di LAMPSchool non è più attivamente sviluppata nè supportata.
Al momento l'unica alternativa è [Registro](https://play.google.com/store/apps/details?id=com.gabriel.Registro&hl=it&gl=US)

**Comment by valerio-bozzolan** [comment]
> L'app di LAMPSchool non è più attivamente sviluppata nè supportata. Al momento l'unica alternativa è [Registro](https://play.google.com/store/apps/details?id=com.gabriel.Registro&hl=it&gl=US)

Qualcuno conosce Tavernini Gabriel? Mi piacerebbe ringraziare anche lui per il suo progetto ma non trovo il codice sorgente della sua app.

**Comment by gmontalbano5ct** [comment]
Va bene grazie. No non conosco tavernini Gabriel.

**Comment by vittodevit** [comment]
> > L'app di LAMPSchool non è più attivamente sviluppata nè supportata. Al momento l'unica alternativa è [Registro](https://play.google.com/store/apps/details?id=com.gabriel.Registro&hl=it&gl=US)
> 
> Qualcuno conosce Tavernini Gabriel? Mi piacerebbe ringraziare anche lui per il suo progetto ma non trovo il codice sorgente della sua app.

https://github.com/GabrielTavernini/Registro

**Comment by tommasiangelo01** [comment]
Sarebbe bello se anche l'app lampschool tornasse a funzionare ma soprattutto sarebbe ancora più bello se questa fosse arricchita di richieste fatte da tutte le scuole italiane in questi lunghi anni.

**Comment by valerio-bozzolan** [comment]
@tommasiangelo01 provi l'app segnalata, è sempre software libero compatibile con LAMPSchool:

https://github.com/GabrielTavernini/Registro
