### ISSUE TITLE
Problema inserimento supplenze

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#49]
Buona sera ho riscontrato dei problemi sull inserimento supplenze 
![Uploading IMG_20211101_233032.jpg…]

Mi da quest errore

**Comment by valerio-bozzolan** [comment]
Scusi credo sia necessario ricaricare l'allegato. Grazie mille!

**Comment by gmontalbano5ct** [comment]
Scusi ho risolto grazie ancora
