### ISSUE TITLE
problema email reset password

### ISSUE THREAD

**Issue by andreazanardo2002** [scaforchio/LAMPSchool#5]
buonasera, ho un problema, dove posso configurare i dati  per il server della posta in uscita? attualmente quando un utente chiede il reset della password non gli arriva nessuna email

**Comment by tommasiangelo01** [comment]
BUONGIORNO , E' DA GIORNI CHE LA MIA SCUOLA STA CERCANDO DI ATTIVARE ALL'INTERNO DEL REGISTRO ELETTRONICO LAMPSCHOOL  IL SISTEMA PER FAR GIUSTIFICARE LE ASSENZE DIRETTAMENTE AI GENITORI DEGLI ALUNNI , CON SCARSI RISULTATI .SAREBBE POSSIBILE AVERE UNA PICCOLA GUIDA PDF CHE SPIEGHI COME SI FA? INOLTRE RICORDO TEMPO FA DI AVER FATTO UNA RICHIESTA SULL'INSERIMENTO MASSIVO DI UN COMMENTO RELATIVO AD UN VOTO DI INTERROGAZIONE O VERIFICA SCRITTA.INOLTRE VORREI , SE FOSSE POSSIBILE , GESTIRE LE ASSENZE,I RITARDI E LE USCITE IN UN UNICA SEZIONE , PERCHÉ' CI SIAMO ACCORTI DI UNA CONFUSIONE CHE SI FACEVA NEL METTERE LE ASSENZE POI TORNARE INDIETRO PER METTERE I RITARDI O LE USCITE .PER QUEST'ANNO DOVREBBE ESSERE PREVISTA L'IMPLEMENTAZIONE  DI VARIE OPZIONI RELATIVE ALLE LEZIONE IN MODALITÀ  MISTA,DDI,IN PRESENZA, COSA CHE NON VEDO IN LAMPSCHOOL.

**Comment by tommasiangelo01** [comment]
Mi scusi , utilizzando lampschool , i diversi colleghi mi stanno chiedendo se esiste un modo per indicare nel registro di classe , in caso di supplenza anche il docente che si sta andando a sostituire per questione di trasparenza oltre che di correttezza .Grazie mille

**Comment by mrBackSlash-it** [comment]
> buonasera, ho un problema, dove posso configurare i dati per il server della posta in uscita? attualmente quando un utente chiede il reset della password non gli arriva nessuna email

Penso che i dati per l'SMTP si trovino nella sezione dedicata alle flag dal pannello dell'utente `adminlamp`, ma non ne sono sicuro, farò delle prove oggi sulla mia installazione di test.

> BUONGIORNO , E' DA GIORNI CHE LA MIA SCUOLA STA CERCANDO DI ATTIVARE ALL'INTERNO DEL REGISTRO ELETTRONICO LAMPSCHOOL IL SISTEMA PER FAR GIUSTIFICARE LE ASSENZE DIRETTAMENTE AI GENITORI DEGLI ALUNNI , CON SCARSI RISULTATI .SAREBBE POSSIBILE AVERE UNA PICCOLA GUIDA PDF CHE SPIEGHI COME SI FA? INOLTRE RICORDO TEMPO FA DI AVER FATTO UNA RICHIESTA SULL'INSERIMENTO MASSIVO DI UN COMMENTO RELATIVO AD UN VOTO DI INTERROGAZIONE O VERIFICA SCRITTA.INOLTRE VORREI , SE FOSSE POSSIBILE , GESTIRE LE ASSENZE,I RITARDI E LE USCITE IN UN UNICA SEZIONE , PERCHÉ' CI SIAMO ACCORTI DI UNA CONFUSIONE CHE SI FACEVA NEL METTERE LE ASSENZE POI TORNARE INDIETRO PER METTERE I RITARDI O LE USCITE .PER QUEST'ANNO DOVREBBE ESSERE PREVISTA L'IMPLEMENTAZIONE DI VARIE OPZIONI RELATIVE ALLE LEZIONE IN MODALITÀ MISTA,DDI,IN PRESENZA, COSA CHE NON VEDO IN LAMPSCHOOL.

Per quanto riguarda le funzionalità aggiuntive, il software è concesso sotto licenza AGPLv3, quindi senza alcuna garanzia, essendo gratuito. Per quanto riguarda il problema delle giustificazioni, nella mia scuola sono attive, farò delle prove oggi sulla mia installazione di test.

**Comment by tommasiangelo01** [comment]
Buongiorno,grazie mille per la risposta immediata.Attendo  con ansia
l'esito delle prove di oggi pomeriggio


Il giorno ven 21 mag 2021 alle ore 08:22 Vittorio Lo Mele <
***@***.***> ha scritto:

**Comment by tommasiangelo01** [comment]
Buongiorno,le volevo chiedere solo l'esito in merito alla prova che avrebbe effettuato nel portale lampschool per quanto riguarda le giustificazioni direttamente dal profilo genitore/tutore

**Comment by tommasiangelo01** [comment]
Inoltre vorrei sapere se è possibile indicare ogni volta il docente e la materia che si va a sostituire in caso di una eventuale supplenza.Se è possibile vorrei sapere se esiste un modo per  inviare direttamente via mail  le credenziali di accesso al registro in modo massivo alle famiglie interessate

**Comment by mrBackSlash-it** [comment]
> Buongiorno,le volevo chiedere solo l'esito in merito alla prova che avrebbe effettuato nel portale lampschool per quanto riguarda le giustificazioni direttamente dal profilo genitore/tutore

Buon pomeriggio,
ho fatto delle prove ieri e non sono riuscito, su installazione pulita, ad abilitare la gestione delle assenze DAD per gli insegnanti, quindi neanche la giustificazione autonoma da parte del tutore sul registro. In linea di massima bisognerebbe configurare qualche flag e settare il server per l'invio SMS. Se si sta riferendo alla funzione per giustificare le assenze "classiche, non DAD", non mi risulta sia mai stata implementata una funzione di giustifica online per il tutore.

Per quanto riguarda la sostituzione non mi sono mai informato, bisognerebbe chiedere al prof. Tamburrano.

In fine, per quanto riguarda l'invio in massa via mail delle credenziali, di nuovo, non mi risulta sia mai stata implementata una funzione del genere, so solo che si possono stampare.

**Comment by mrBackSlash-it** [comment]
> Penso che i dati per l'SMTP si trovino nella sezione dedicata alle flag dal pannello dell'utente `adminlamp`, ma non ne sono sicuro, farò delle prove oggi sulla mia installazione di test.

In ogni caso mi correggo, a quanto pare lampschool utilizza la funzione `mail()` del PHP e non ha nessuna implementazione del protocollo SMTP. Molto probabilmente, siccome la funzione mail è abbastanza "rudimentale", c'è un'altissima probabilità che il messaggio venga bloccato da filtri antispam o policy varie dei provider più comuni come gmail.

**Comment by andreazanardo2002** [comment]
Ok grazie

**Comment by tommasiangelo01** [comment]
BUONGIORNO,PURTROPPO NELLLA VERSIONE 2020.11 , ABBIAMO RISCONTRATO NUMEROSE
DIFFICOLTA' CON LE NUOVE IMPLEMENTAZIONI COME AD ESEMPIO QUANDO VADO A FARE
LO SCRUTINIO PER OBIETTIVO MI ESCE IL SEGUENTE AVVISO

**Comment by tommasiangelo01** [comment]
OPPURE QUANDO VADO SUL TABELLONE DELLO SCRUTINIO E CLICCO OB MI ESCE IL
SEGUENTE AVVISO

**Comment by tommasiangelo01** [comment]
PER NON PARLARE DI QUANDO ENTRO COME UTENTE ESAMIDISTATO NELL'AREA "MATERIE
ESAME" MI DA IL SEGUENTE MESSAGGIO (VISUALIZZABILE NELLA FOTO ALLEGATA) ,
CHE POI NON MI PERMETTE LA COMPILAZIONE DEI TABELLONI E CERTIFICAZIONI
D'ESAME  , INSOMMA , NON MI PERMETTE DI SVOLGERE NIENTE,MA QUESTO SUCCEDE
SOLO QUANDO  RIPORTO LA MIA SCUOLA AL LIVELLO 4 , OSSIA , SCUOLA SUPERIORE

**Comment by tommasiangelo01** [comment]
Buonasera,voglio riportarvi alcune critiche incontrate nella piattaforma
LAMPSCHOOL,in quanto ho verificato da più installazioni il malfunzionamento
dell'ultima funzione integrata,ossia,scrutinio obiettivi
apprendimento,quest'ultima non funziona sia quando il docente cerca di
caricare gli stessi obiettivi che quando il preside cerca di stampare in
sede di scrutinio le schede degli stessi obiettivi di
apprendimento.Dunque,sarebbe auspicabile procedere alla risoluzione del
seguente problema , in quanto le schede di valutazioni delle scuole
primarie devono seguire le norme ministeriali , grazie.Nel caso in cui il
problema si verificasse solo nel mio istituto , sono disposto a darvi le
credenziali per accedere ad Altervista e sistemare il tutto , anche perchè
questo non è l'unico problema da me riscontrato, ce ne sono un bel
pò,ragione per la quale avrei bisogno di fornirvi le credenziali in modo da
accedere e e sistemare il tutto.Grazie mille

**Comment by mrBackSlash-it** [comment]
> sono disposto a darvi le credenziali per accedere ad Altervista e sistemare il tutto
Buongiorno, da test effettuati in precedenza è stato determinato che Altervista è un' hosting incompatibile con Lampschool, siccome causa instabilità e comportamenti imprevedibili. Le consigliamo di passare ad un hosting come Aruba o installare lo stack LAMP/LEMP ed in seguito Lampschool su una VPS o Dedicato.

**Comment by tommasiangelo01** [comment]
Buonasera, sarebbe possibile da parte vostra,gentilmente installarmi lo
stack LAMP/LEMP ed inseguito eseguire LAMPSCHOOL su una VPS , in quanto io
non sono molto pratico in questo campo?Grazie mille per la pazienza
infinita

Il giorno mar 27 lug 2021 alle ore 11:24 Vittorio Lo Mele <
***@***.***> ha scritto:
