### ISSUE TITLE
Sistemare conteggio media

### ISSUE THREAD

**Issue by vittodevit** [scaforchio/LAMPSchool#51]
Il conteggio della media si falsa quando la materia ha voti vuoti con solo giudizio.
Appena possibile apro PR con fix. (screenshot fatta in production)
![image](https://user-images.githubusercontent.com/58268988/140028260-66ac9f01-349b-4318-af08-e10aee56c79a.png)

**Comment by scaforchio** [comment]
Abbiamo risolto con @vittodevit .

**Comment by gmontalbano5ct** [comment]
Buona sera ma già questo è stato risolto?

**Comment by valerio-bozzolan** [comment]
> Buona sera ma già questo è stato risolto?

Sì.

Per saperlo ho semplicemente letto il messaggio prima. Cosa che consiglio :)
