### ISSUE TITLE
Problema trimestri

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#54]
Volevo chiedervi se potevate mette anche la possibilità dei trimestri perché riesco a mettere solo i quadrimestri poi un altra domanda come faccio ad aggiornare il registro con le vostre modifiche  senza cancellare tutti i dati e rimetterli ?

**Comment by vittodevit** [comment]
Per i trimestri è un calvario e servono finanziamenti, per quanto riguarda invece gli aggiornamenti ti basta fare
`git pull`
nella cartella in cui hai installato il registro oppure se hai caricato i file in modi alternativi segui le modalità del file
[INSTALL.md](https://github.com/scaforchio/LAMPSchool/blob/master/INSTALL.md)

**Comment by gmontalbano5ct** [comment]
Ok grazie da quanto ho capito per l aggiornamento bisogna togliere tutte le cartelle e lasciare solo ABC e lampschol data?

**Comment by vittodevit** [comment]
> Ok grazie da quanto ho capito per l aggiornamento bisogna togliere tutte le cartelle e lasciare solo ABC e lampschol data?

Ed anche buffer. Se invece hai installato facendo clone da github ripeto basta fare `git pull`

**Comment by gmontalbano5ct** [comment]
Ok ripeto per paura di perdere i dati eliminare tutti i file tranne buffer, lampschol data e ABC ?
