### ISSUE TITLE
Problema grave

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#56]
Buonasera siamo quasi alla fine della chiusura del trimestre e facendo delle simulazioni si sono presentati dei problemi:nelle pagelle intermedie non esce il comportamento e né tanto meno il giudizio dello stesso ,stessa cosa ho riscontrato nei tabelloni di scrutinio dove non appare il voto di comportamento.

**Comment by vittodevit** [comment]
Descrivi meglio il problema, sono stati inseriti i voti? Ci sono messaggi di errore?

**Comment by tommasiangelo01** [comment]
Sto parlando della disciplina comportamento ,ebbene sì , i voti/giudizi del comportamento sono stati inseriti ma non appaiono nel tabellone scrutinio pdf che si va a stampare ,mentre nella pagella pdf non compare proprio la disciplina comportamento

**Comment by gmontalbano5ct** [comment]
@tommasiangelo01 come hai fatto ad inserire i trimestri? io non ci riesco  puoi spiegarmelo ?

**Comment by vittodevit** [comment]
Prova a mandare qualche screen e domani vedo di darci un'occhiata.

**Comment by tommasiangelo01** [comment]
Di fatto neanche io ho capito , ma la mia scuola ha impostato la chiusura del primo scrutinio a dicembre ,anche se di base resta la scritta quadrimestre in quanto non abbiamo capito come impostare il trimestre

**Comment by tommasiangelo01** [comment]
Avevo infatti proposto di aprire un nuovo canale Youtube sempre aggiornato dove riportare tutti i tutorial sulle novità e sugli aggiornamenti , ma anche sulle soluzioni in merito alle difficoltà che si incontrano nel portale lampschool

**Comment by tommasiangelo01** [comment]
Sarebbe bello se ci fossero anche gli scrutini integrativi , cosa ormai obbligatoria in tutti i registri

**Comment by tommasiangelo01** [comment]
Allora per quanto riguarda la problematica che avevo riportato prima in merito al voto di comportamento che non appariva, ho risolto .

**Comment by tommasiangelo01** [comment]
L'unica problematica sarebbe il giudizio sulla scheda di valutazione 
Prima di tutto è troppo piccolo , neanche con gli occhiali riesco a vederlo  e poi il riquadro in cui si trova il giudizio non ha né un inizio e né una fine ,dovrebbe essere un semplice rettangolo in cui compare un bel giudizio carattere 12 se non di più in modo che tutti possano riuscire a leggere ciò che è scritto .Un'altra cosa nel giudizio, soprattutto nelle frasi in qui vi sono gli apostrofi , mi si presenta questo problema che allego ,stessa cosa per i tabelloni , anche questi troppo piccoli i caratteri , il tabellone si dovrebbe estendere su tutta la pagina ed essere bello visibile anche dalla bacheca allego foto anche di questa 

https://drive.google.com/file/d/1lkEw2E1muqzoaehHx-0VWlWBnN9pQP-8/view?usp=sharing

mentre questo è il modello completo di tabellone scrutinio  di grande dimensione che il registro dovrebbe avere

https://drive.google.com/file/d/1VSw_ABfPcf7h62coYYCKDzwlPQUwAE2g/view?usp=sharing

**Comment by gmontalbano5ct** [comment]
@vittodevit mi può spiegare come si fa ad inserire il trimestre?

**Comment by valerio-bozzolan** [comment]
> Allora per quanto riguarda la problematica che avevo riportato prima in merito al voto di comportamento che non appariva, ho risolto .

**Comment by valerio-bozzolan** [comment]
(Il seguente messaggio può essere ignorato da Vittorio e Pietro)

Devo chiedere una serie di cose di buon senso e collaborazione, per rispettare il prezioso tempo dei volontari Vittorio e Pietro e tutti gli altri volontari. Inoltre, la loro voglia di contribuire è ancora più preziosa e dobbiamo cercare di non mandarli in burnout. Ecco come:

* diamo un titolo costruttivo e significativo a queste comunicazioni. Idealmente dall'oggetto qualsiasi estraneo dovrebbe riuscire a farsi un'idea di cosa viene richiesto o quale sia il problema. "Problema grave" è un titolo non accettabile, nè costruttivo nè significativo. Cerchiamo di modificare ora questo titolo per spiegare qual è il problema. Se non ci si riesce perché i problemi o le idee sono troppe, allora è meglio ad iniziare a descrivere solo il problema più importante, descrivendo le successive questioni solo se il primo problema è risolto o non è risolvibile o se è passato qualche momento di tempo per dare un po' di respiro.
* non rispondiamo via mail ma online, per evitare che venga voglia di mandare due messaggi di fila o altri problemi
* non rispondiamo mai 2 volte di fila ai propri messaggi (4 volte è proprio troppo). Oltretutto se i messaggi successivi sono a mezzanotte o al mattino presto. Notifiche che arrivano a tutti. Il rischio che un volontario si stufi e silenzi le notifiche del progetto è troppo alto e sarebbe catastrofico. Invece che mandare due messaggi consecutivi bisogna modificare il proprio ultimo messaggio. Si fa online, premendo il tasto a destra della "faccina" vicina al proprio messaggio e cliccando "Edit". Modificare il proprio ultimo messaggio serve a renderli più chiari, meno dispersivi, ed evitare due notifiche consecutive. Serve inoltre a far risparmiare tempo di lettura a tutti i volontari, dato che più messaggi ci sono più tempo dovranno investire anche solo per capire come essere utili.
* come accennato pochi giorni fa non è al momento accettabile usare Google Drive per condividere una immagine in questi commenti. Devo chiedere per cortesia di trascinare l'immagine direttamente in questi commenti (cosa che funziona online)

Questo è davvero l'unico modo per far sì che le cose siano fatte "con urgenza" dai volontari Pietro e Vittorio. Invito certamente a riaprire questa issue solo quando questi problemi saranno stati letti e risolti, nel frattempo che mi pare di capire che Vittorio stia risolvendo comunque.

Grazie scusatemi
