### ISSUE TITLE
Attivazione GitHub Projects

### ISSUE THREAD

**Issue by vittodevit** [scaforchio/LAMPSchool#57]
Propongo di attivare sulla repository la funzione gratuita di GitHub **"Projects"**.
Le richieste sono tante, e tenere tracca delle high priority o finanziamenti e linkare le pull request sta diventando complicato.
Questo strumento può essere utile: [documentazione qui](https://docs.github.com/en/issues/trying-out-the-new-projects-experience/about-projects)

Allego screenshot dimostrative:`
![1](https://docs.github.com/assets/images/help/issues/projects_table.png)
![12](https://docs.github.com/assets/images/help/issues/projects_board.png)
![image](https://user-images.githubusercontent.com/58268988/140323809-6dadaca1-c34a-4580-811b-cbcc6a66bc0e.png)

**Comment by valerio-bozzolan** [comment]
Ciao Vittorio! Hai i permessi di modificare le colonne a piacimento giusto?

https://github.com/scaforchio/LAMPSchool/projects

**Comment by vittodevit** [comment]
> Ciao Vittorio! Hai i permessi di modificare le colonne a piacimento giusto?
> 
> [scaforchio/LAMPSchool/projects](https://github.com/scaforchio/LAMPSchool/projects)

Scusami se ti rispondo solo adesso, comunque no, non me le fa modificare.

**Comment by valerio-bozzolan** [comment]
Per non disturbare Pietro se vuoi dimmi pure come lo vorresti e lo cambio subito. Poi lo vedrete meglio insieme tanto. Ciau!

**Comment by vittodevit** [comment]
Perfetto, mi basta avere le:

- Proposte
- Low Priority
- High Priority
- Finanziate
- Work In Progress
- Completate

**Comment by vittodevit** [comment]
Perfetto, manca la possibilità di aggiungere le card ma è questione di permessi e possiamo sistemare con Pietro! Grazie mille

**Comment by valerio-bozzolan** [comment]
Non so se sia utile la colonna "Finanziate". Forse è meglio guardare se il task è assegnato o meno a qualcuno. Dai, quelle che sto cercando di finanziare me le assegno simbolicamente per semplificare.

**Comment by valerio-bozzolan** [comment]
Mi sono permesso di piazzare emojii a caso. asd

**Comment by vittodevit** [comment]
Ottima organizzazione, assegna a me invece l'invio delle mail. Appena possibile do un occhiata.

**Comment by valerio-bozzolan** [comment]
> Ottima organizzazione, assegna a me invece l'invio delle mail. Appena possibile do un occhiata.

Alla grande!

* https://github.com/scaforchio/LAMPSchool/issues/22
