### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#59]
Buongiorno ,una piccola richiesta dal punto di vista grafico /estetico:sarebbe possibile rendere tutti i voti sia per lato docente che genitore in grassetto e di colore bianco o sarebbe un problema per la stampa ?Chiedo questo perché non si intona molto bene il colore nero del voto con la cella verde .Grazie mille

**Comment by tommasiangelo01** [comment]
Poi ho pensato che sarebbe bello elaborare per il lato docente una schermata più fresca ed intuitiva che suddivida le varie tipologie di verifiche ,in questo modo ,sarebbe molto utile ,dal momento che nel riepilogo lezioni non si riesce a vedere tutte le valutazioni e assenze in un'unica sezione  in quanto i giorni avanzano sempre di più e c'è la necessità di spostarsi con il cursore da sinistra a destra e così facendo ,si perde anche il riferimento ossia:il nome e cognome degli alunni e il numero alfabetico.

Allego l'immagine che sarebbe molto utile per mediare  a questo piccolo e importante problema 
https://drive.google.com/file/d/18QkVcTib2Pj-PqgdUHi0uk8u5b9Zd4_d/view?usp=sharing

**Comment by gmontalbano5ct** [comment]
@tommasiangelo01 scusi volevo chiederle se mi poteva mandare le credenziali del docente demo per vedere come è strutturato e anche per prendere spunto per qualche modifica a lampschol grazie

**Comment by scaforchio** [comment]
I voti sono già divisi per tipologia in altre schermate che consentono di calcolare le medie, ecc. 
L'aspetto grafico, come ha detto @valerio-bozzolan non è a momento una priorità.

**Comment by valerio-bozzolan** [comment]
Buonasera @tommasiangelo01!

Riesce a riassumere queste proposte qui?

https://github.com/scaforchio/LAMPSchool/issues/12

Grazie mille per l'aiuto così non moltiplichiamo le pagine sui cambiamenti grafici.

**Comment by tommasiangelo01** [comment]
Ho pensato alla possibilità di aggiungere questa tendina che permette di cambiare anno scolastico ,in modo da consultare anche gli anni passati e tenere tutto conservato .Allego immagine 

https://user-images.githubusercontent.com/69850072/140663697-40627dcc-7253-4560-ba46-06319cb4d78a.png

**Comment by vittodevit** [comment]
Lavoro immane fare una cosa del genere, per il momento è impossibile.
