### ISSUE TITLE
File mancante ./lib/inc_inizializzazione.php 

### ISSUE THREAD

**Issue by andreazanardo2002** [scaforchio/LAMPSchool#6]
salve, in tutte le schermate visualizzo. questo errore, qualcuno riesce ad aiutarmi? 

Warning: include_once(./lib/inc_inizializzazione.php): failed to open stream: No such file or directory in /home/zanchicl/domains/thoc.it/public_html/registro/php-ini.php on line 23

Warning: include_once(): Failed opening './lib/inc_inizializzazione.php' for inclusion (include_path='.:/opt/alt/php71/usr/share/pear') in /home/zanchicl/domains/thoc.it/public_html/registro/php-ini.php on line 23

**Comment by mrBackSlash-it** [comment]
Sembra appunto, come descritto dall'errore, manchi quel file (`./lib/inc_inizializzazione.php`). Provi a controllare in quella directory se il file effettivamente manca o è solo un problema di permessi.

**Comment by mrBackSlash-it** [comment]
Aprendo il file mi sono accorto che l'errore "non si può evitare", siccome per far funzionare il file e non dover includere check, a scanso di equivoci, prova ad aprire sia con `./` che con `../` il file in questione. L'unico modo per disabilitare i messaggi di errore è disattivare l'error reporting del PHP.
