### ISSUE TITLE
Domanda sistemazione media voti

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#60]
Una domanda ma il problema che quando si inserisce una nota nel voto senza il voto la media si altera questo problema è stato risolto?

**Comment by vittodevit** [comment]
> Una domanda ma il problema che quando si inserisce una nota nel voto senza il voto la media si altera questo problema è stato risolto?

Certo, è stato risolto da giorni, puoi procedere all'aggiornamento

**Comment by gmontalbano5ct** [comment]
Ok grazie
