### ISSUE TITLE
gestione orario docenti 

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#62]
non riesco ad inserire l'orario al docente? come si fa?

**Comment by scaforchio** [comment]
Le tabelle per la visualizzazione dell'orario dei docenti sono importate da applicazioni esterne (attualmente funziona con le tabelle di OrarioFacile).

**Comment by gmontalbano5ct** [comment]
Come faccio ad inserirle nel registro?

**Comment by gmontalbano5ct** [comment]
Mi può inviare il sito del programma?

**Comment by vittodevit** [comment]
https://www.orariofacile.com/

**Comment by gmontalbano5ct** [comment]
@vittodevit 
![Screenshot_2021-11-07-11-11-16-977_com android chrome](https://user-images.githubusercontent.com/93207960/140640794-f098ff17-3ac2-4ae9-8690-55c64240cbd5.jpg)

**Comment by gmontalbano5ct** [comment]
Mi da quest errore

**Comment by gmontalbano5ct** [comment]
Ho risolto scusi

**Comment by gmontalbano5ct** [comment]
Ascolti come faccio ad inserire l orario nel registro

**Comment by gmontalbano5ct** [comment]
ho bisogno di sapere come inserire l'orario dei docenti nel registro per favore grazie

**Comment by vittodevit** [comment]
Siccome non ho voglia di riscrivere il papiro, rimando a #67, in particolare il [mio messaggio lunghissimo](https://github.com/scaforchio/LAMPSchool/issues/67#issuecomment-963271496).

**Comment by gmontalbano5ct** [comment]
ho letto ma cosa vuole dire mi scusi?

**Comment by gmontalbano5ct** [comment]
e poi mi può dire come inserire l'orario con facile.com?

**Comment by vittodevit** [comment]
Noi lo sviluppiamo il registro, non forniamo assistenza.
Tra l'altro mi occupo di una sezione totalmente diversa del registro quindi non saprei assisterti comunque, anche perchè faccio volontariato ed il tempo che posso dedicare è poco.

Per maggiori informazioni vedi le info su `Assistenza Commerciale` nella homepage quì su GitHub.

Citando la licenza sotto cui è distribuito questo software: 

> 15. Rinuncia alla Garanzia
> NON C’E’ NESSUNA GARANZIA PER IL PROGRAMMA, PER QUANTO CONSENTITO
> DALLE VIGENTI NORMATIVE. ECCETTO QUANDO ALTRIMENTI STABILITO PER
> ISCRITTO, I DETENTORI DEL COPYRIGHT E/O LE ALTRE PARTI FORNISCONO
> IL PROGRAMMA “COSI’ COME È” SENZA GARANZIA DI ALCUN TIPO, NE’ ESPRESSA
> NE’ IMPLICITA, INCLUSE, MA NON LIMITATE A, LE GARANZIE DI COMMERCIABILITA’
> O DI UTILIZZABILITA’ PER UN PARTICOLARE SCOPO. L’INTERO RISCHIO CONCERNENTE
> LA QUALITA’ E LE PRESTAZIONI DEL PROGRAMMA E’ DEL LICENZIATARIO.
> SE IL PROGRAMMA DOVESSE RISULTARE DIFETTOSO, IL LICENZIATARIO SI
> ASSUME I COSTI DI MANUTENZIONE, RIPARAZIONE O CORREZIONE.
> 16. Limitazione di Responsabilità
> IN NESSUN CASO, A MENO CHE NON SIA RICHIESTO DALLA NORMATIVA
> VIGENTE O CONCORDATO PER ISCRITTO, I DETENTORI DEL COPYRIGHT, O
> QUALUNQUE ALTRA PARTE CHE MODIICA E/O DISTRIBUISCE IL PROGRAMMA
> SECONDO LE CONDIZIONI PRECEDENTI, POSSONO ESSERE RITENUTI RESPONSABILI
> NEI CONFRONTI DEL LICENZIATARIO PER DANNI, INCLUSO QUALUNQUE DANNEGGIAMENT
> GENERICO, SPECIALE, INCIDENTALE O CONSEQUENZIALE DOVUTO ALL’USO
> O ALL’IMPOSSIBILITA’ D’USO DEL PROGRAMMA (INCLUSI, MA NON LIMITATI
> A, LE PERDITE DI DATI, LA CORRUZIONE DI DATI, LE PERDITE SOSTENUTE
> DAL LICENZIATARIO O DA TERZE PARTI O L’IMPOSSIBILITA’ DEL PROGRAMMA
> A FUNZIONARE ASSIEME AD ALTRI PROGRAMMI), ANCHE NEL CASO IN CUI
> IL DETENTORE O LE ALTRE PARTI SIANO STATI AVVISATI CIRCA LA POSSIBILITA’
> DI TALI DANNEGGIAMENTI.
> 17. Interpretazione delle Sezioni 15 e 16.
> Se la dichiarazione di garanzia e la limitazione di responsabilità fornite precedentemente
> non hanno effetto legale in un paese a causa delle loro condizioni, le corti di giustizia
> devono applicare la norma locale che più si avvicini al rifiuto assoluto di qualsivoglia
> responsabilità civile relativa al Programma, a meno che una garanzia o una assunzione di
> responsabilità scritta non accompagni una copia del programma ottenuta dietro pagamento.
> 

La versione completa TRADOTTA della licenza è disponibile [qua](http://homeunix.katolaz.net/gplv3/gplv3-it-final.pdf)

**Comment by vittodevit** [comment]
Se il registro LAMPSchool non soddisfa le sue esigienze, non è intenzionato ad usufruire dell'assistenza commerciale e non è, in alternativa, disposto ad organizzare una propria assistenza intra-scolastica assumendo un esperto di PHP, le consigliamo le seguenti valide alternative proprietarie con assistenza telefonica inclusa:

- [DidUP - Argo Software](http://homeunix.katolaz.net/gplv3/gplv3-it-final.pdf)
- [ClasseViva - Spaggiari](https://web.spaggiari.eu/shop/prodotti/classeviva-registro-di-classe)
- [Suite Axios](https://axiositalia.it/wp-content/uploads/2021/07/Listino-2021-new.pdf)
- [Nuvola - Madisoft](https://scuoladigitale.info/)

Se invece vuole organizzare assistenza nel modo che preferisce (commerciale o interna), ma vuole utilizzare sempre un registro libero, le consigliamo il nostro progetto amico, [giua@school](https://github.com/trinko/giuaschool)

**Comment by valerio-bozzolan** [comment]
@gmontalbano5ct mi dispiace per le risposte apparentemente un po' piccate dei miei colleghi volontari ma il punto è che le scuole non possono sperare in assistenza completamente gratuita e ad-hoc da parte di volontari (che già per miracolo scrivono software per specifiche scuole terze senza alcun contributo da esse).

Per risolvere questo problema il dirigente scolastico deve stanziare dei fondi annuali per "sviluppo e assistenza tecnica su applicativi scolastici in PHP" da parte di un essere umano tecnico con competenze PHP. Questo è l'unico modo per integrare in tempi certi le funzionalità richieste e avere una risposta sugli orari.

Spero che qualcuno riesca a rispondervi ma ripetere la domanda al momento non darà una risposta.

**Comment by gmontalbano5ct** [comment]
Ok grazie e mi scusi
