### ISSUE TITLE
problema

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#63]
dopo aver fatto l'aggiornamento e aver lasciato le cartelle buffer,lampschol data e abc mi si sono azzerati tutti i dati.

**Comment by vittodevit** [comment]
> dopo aver fatto l'aggiornamento e aver lasciato le cartelle buffer,lampschol data e abc mi si sono azzerati tutti i dati.

Hai sovrascritto il file `php-ini.php`?
Non dovrebbe causare problemi, ma se hai fatto l'installazione senza suffisso dovresti lasciare intatto `php-ini`.
Ci sono ancora le credenziali del database li dentro?

**Comment by gmontalbano5ct** [comment]
No questo non l ho fatto avevo chiesto cosa fare per l aggiornamento e mi avevate detto di lasciare soltanto ABC,buffer, lampschol data .

**Comment by scaforchio** [comment]
E' probabile che sia successo quello che ha scritto @vittodevit .
Il file php-ini.php nela cartella principale è stato probabilmente sovrascritto. Devi reimpostare i parametri di accesso al database e ritroverai i dati.

**Comment by gmontalbano5ct** [comment]
Ho provato ma niente.

**Comment by valerio-bozzolan** [comment]
Colgo l'occasione per ricordare che la procedura di aggiornamento dice di fare un backup prima, proprio per poter ripristinare tutto in sicurezza in caso di qualsiasi svista umana o anomalia.

@gmontalbano5ct purtroppo non penso che Pietro o Vittorio possano risolvere il suo problema senza metterci le mani o senza ulteriori dettagli. Chiudo questa segnalazione. Se posso provare a fare miracoli sentiamoci in privato. Quando vuole:

348 702 7731

direttore@linux.it

Grazie
