### ISSUE TITLE
Link assente in login page ('Ritorna ad home page')

### ISSUE THREAD

**Issue by zerai** [scaforchio/LAMPSchool#64]
Cliccando sul link 'Ritorna ad home page' la pagina non cambia
![Screenshot from 2021-11-06 16-14-05](https://user-images.githubusercontent.com/2405279/140614773-4900bb9f-8be1-4621-a2d5-a58db5f13810.png)
.

Dettaglio attuale link:
![Screenshot from 2021-11-06 16-13-44](https://user-images.githubusercontent.com/2405279/140614789-ae166a5e-08d4-4d00-af4b-df548800f269.png)

Possibile soluzione:
```html
<a href="/" target="_top">Ritorna ad home page</a>
```

**Comment by scaforchio** [comment]
Il link per il ritorno alla homepage è specificato in un parametr di configurazione, basta cambiare quello per avere il link corretto.

**Comment by zerai** [comment]
Risolto, grazie!

E' una mia opinione personale, ma sarebbe utile evidenziare in qualche modo i parametri che andrebbero 'obligatoriamente' cambiati dopo l'installazione (pena malfunzionamento).
