### ISSUE TITLE
Bug media voti lato tutor/alunno

### ISSUE THREAD

**Issue by rodolfo024** [scaforchio/LAMPSchool#65]
Volevo segnalare che la media risulta alterata quando insieme ai voti tradizionali ci sono dei giudizi senza voto come "giustifica" ecc... allego screenshot. Questo problema non sussiste e non lo è mai stato dal lato docenti.
![mediavoti](https://user-images.githubusercontent.com/76261684/140620848-e8c2c2dc-9ac6-4ced-93b3-90640cb3d79a.PNG)

**Comment by vittodevit** [comment]
Aggiorna LAMPSchool, il problema è stato fixato nell'ultimo commit.

**Comment by tommasiangelo01** [comment]
Si potrebbe realizzare sia per il lato genitore che docente una legenda dei voti in base al colore ,ossia : rosso=valutazione negativa , verde=valutazione positiva ;blu=valutazione che non concorre alla media ;giallo=si giustifica; arancio=dimentica il materiale
