### ISSUE TITLE
Inserimento autorizzazione uscita anticipata con alunno assente.

### ISSUE THREAD

**Issue by vittodevit** [scaforchio/LAMPSchool#67]
**FILE:** `assenze/selealunniautuscita.php`

**INTERVENTI:**
Nel ciclo che si occupa di stampare la tabella degli alunni, disabilitare gli assenti, per impedire l'inserimento di autorizzazioni su alunni che sono assenti, evitando incongruenze nei dati.

@valerio-bozzolan o @scaforchio assegnate a me e mettete tag High Priority e Bug, spostate in colonna Work In Progress, stasera o domani dovrei aprire PR.

**Comment by tommasiangelo01** [comment]
Buongiorno ,durante l'inserimento di voto da parte del docente,oltre alla colonna con il nominativo degli alunni,la data di nascita ,le ore di assenza e le tre tipologie di valutazioni (scritta-orale-pratica) si potrebbe aggiungere un'altra colonna che riporti il numero di voti in modo da sapere chi è stato già interrogato?Lo chiedo perché tante volte mi capita di andare a mettere una valutazione ad alunni che ho già sentito e che quindi ha già una valutazione .Sarebbe fattibile ?

**Comment by vittodevit** [comment]
> Buongiorno ,durante l'inserimento di voto da parte del docente,oltre alla colonna con il nominativo degli alunni,la data di nascita ,le ore di assenza e le tre tipologie di valutazioni (scritta-orale-pratica) si potrebbe aggiungere un'altra colonna che riporti il numero di voti in modo da sapere chi è stato già interrogato?Lo chiedo perché tante volte mi capita di andare a mettere una valutazione ad alunni che ho già sentito e che quindi ha già una valutazione .Sarebbe fattibile ?

# Versione corta:

Si è fattibile, ma ve lo chiedo scongiurandovi, riferito sia a lei che agli altri abituali commentatori e reporter.
**PER FAVORE**, per ogni problema e richiesta apritene una nuova, siccome se le mettete dentro altre cose che non centrano nulla, il lavoro per me ed altri contributor diventa impossibile. Io sto impazzendo a stare dietro a tutte le richieste e disturbo sempre il povero @valerio-bozzolan per spostare card e mettere label.
Le regole generali per postare sono queste (non solo qui, ma in quasi ogni progetto open).
- Nuovo problema? Nuova discussione!
- Problema già trattato? Si riprende la discussione precedente.
- Oggetti delle richieste chiari.

Citando lui, eccoti la versione più lunga.

-------

# Versione lunga:

@valerio-bozzolan 4 giorni fa ha scritto [questo](https://github.com/scaforchio/LAMPSchool/issues/56#issuecomment-960518219)

(Il seguente messaggio può essere ignorato da Vittorio e Pietro)

Devo chiedere una serie di cose di buon senso e collaborazione, per rispettare il prezioso tempo dei volontari Vittorio e Pietro e tutti gli altri volontari. Inoltre, la loro voglia di contribuire è ancora più preziosa e dobbiamo cercare di non mandarli in burnout. Ecco come:

* diamo un titolo costruttivo e significativo a queste comunicazioni. Idealmente dall'oggetto qualsiasi estraneo dovrebbe riuscire a farsi un'idea di cosa viene richiesto o quale sia il problema. "Problema grave" è un titolo non accettabile, nè costruttivo nè significativo. Cerchiamo di modificare ora questo titolo per spiegare con brevità qual è il problema. Se non ci si riesce perché i problemi o le idee sono troppe, allora è meglio iniziare a descrivere solo quello più importante, descrivendo le successive questioni solo se il primo problema è risolto o non è risolvibile o se è passato almeno qualche momento di tempo per dare un po' di respiro ai volontari (esempio non accettabile in futuro: [Elenco di aspetti da migliorare #13](https://github.com/scaforchio/LAMPSchool/issues/13)).
* in ogni caso il fatto che una questione sia urgente è purtroppo un dettaglio marginale per un volontario, quindi scriviamolo in fondo al messaggio (non nel titolo appunto) e magari nella forma "Grazie per tutto. Segnalo che questa questione è abbastanza critica per la nostra realtà. Grazie per l'aiuto". L'urgenza non velocizza la lettura e la comprensione del problema da parte di un volontario.
* non rispondiamo via mail ma online, per evitare che venga voglia di mandare due messaggi di fila o altri problemi
* non rispondiamo mai 2 volte di fila ai propri messaggi (4 volte è proprio troppo). Oltretutto se i messaggi successivi sono a mezzanotte o al mattino presto. Notifiche che arrivano a tutti. Il rischio che un volontario si stufi e silenzi le notifiche del progetto è troppo alto e sarebbe catastrofico. Invece che mandare due messaggi consecutivi bisogna modificare il proprio ultimo messaggio. Si fa online, premendo il tasto a destra della "faccina" vicina al proprio messaggio e cliccando "Edit". Modificare il proprio ultimo messaggio serve a renderli più chiari, meno dispersivi, ed evitare due notifiche consecutive. Serve inoltre a far risparmiare tempo a tutti i volontari. Più messaggi ci sono, più tempo dovranno investire anche solo per capire come essere utili.
* non è al momento accettabile usare Google Drive per condividere una immagine. Devo chiedere per cortesia di trascinare l'immagine direttamente in questi commenti (cosa che funziona online) per poi togliere il link di Google Drive superfluo
* segnalando un problema è molto probabile che la stessa domanda sarà posta in futuro da altri. È quindi necessario, se si risolve da sè, spiegare il come, per valorizzare il proprio intervento, dando un contributo significativo.

Queste cose sono strategiche per migliorare l'efficienza con cui i propri problemi vengono risolti da altri volontari.

Alcune cose che ho scritto sono valide qui, altre in futuro, altre in issue precedenti che sono ancora aperte ora. La premessa è che comprendiamo le urgenze scolastiche ma ora bisogna comprendere i volontari. Garantisco che tutto questo aiuta ad avanzare più in fretta.

## Perchè siamo arrivati a questo punto?
Capisco lo stress di una urgenza. Per evitare queste situazioni di urgenza invito fortemente a contattare il proprio dirigente scolastico, spiegando che la propria scuola non ha alcun contratto di assistenza con nessun developer, neanche un developer junior, ma che l'istituto ha la possibilità di rimediare, stanziando un fondo per pagare una persona di fiducia esperta in PHP e portare così avanti i propri interessi in LAMPSchool in tempi certi (ad esempio finanziando una giornata di lavoro a settimana ad una persona - per un anno). Più info:

* [scaforchio/LAMPSchool#assistenza-commerciale](https://github.com/scaforchio/LAMPSchool#assistenza-commerciale)

## OK ma cosa fare ora?
Invito certamente a riaprire questa issue quando questi problemi saranno stati risolti (e.g. eliminando i propri messaggi obsoleti / "di troppo", accorpandoli in un solo messaggio consecutivo, togliendo link a Google Drive e caricando foto direttamente qui, aggiornando il titolo) per una discussione sintetica, chiara, costruttiva. Tanto mi pare di capire che Vittorio stia comunque cercando di aiutare a risolvere (grazie Vittorio! Santo subito).
 
Dai che si va avanti. Grazie a tutti per la grande collaborazione.

---------

# Versione cortissima
Qualsiasi richiesta che non rispetta le regole di posting sarà cestinata per risparmiare il tempo necessario alla gestione delle relazioni con il pubblico da parte del team di sviluppo.

**Comment by vittodevit** [comment]
Per quanto riguarda il bug **originariamente** assegnato a questo Issue entro stasera o domattina apro PR

**Comment by valerio-bozzolan** [comment]
@vittodevit se posso suggerirei di togliere il "watch" al progetto così cerco di farvi risparmiare tempo facendo da frontend support e pingandovi ogni volta. Che dici?

Ciau

**Comment by vittodevit** [comment]
> @vittodevit se posso suggerirei di togliere il "watch" al progetto così cerco di farvi risparmiare tempo facendo da frontend support e pingandovi io ogni volta che c'è veramente uno sviluppo non lunare. Che dici?
> 
> Ciau

Perfetto, allora inizio a sistemare le cose che servono a scuola da me, eventualmente pingami.

**Comment by vittodevit** [comment]
Sistemato con #80
