### ISSUE TITLE
problema assegnare ruolo staff a docente

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#68]
docenti/attrruolos.php non è presente. 
![Screenshot_2021-11-08-15-54-51-707_com android chrome](https://user-images.githubusercontent.com/93207960/140764404-b78098b9-6d4d-425e-b90d-664094c3d155.jpg)

**Comment by gmontalbano5ct** [comment]
Mi risulta che è inserito

**Comment by valerio-bozzolan** [comment]
Per favore aiuti un estraneo a capire come identificare e riprodurre problema sul suo computer. Personalmente non saprei che passaggi ha effettuato e non saprei aiutarla. Grazie

**Comment by gmontalbano5ct** [comment]
ho tolto tutti i file tranne le cartelle buffer lampschool data abc e i file ini.php
