### ISSUE TITLE
domanda giuia school

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#69]
come si inserisce nel database ? è come questo l'installazione?

**Comment by valerio-bozzolan** [comment]
Eh?

**Comment by gmontalbano5ct** [comment]
Scusi l installazione di Giulia School è uguale all installazione di lamp School?

**Comment by valerio-bozzolan** [comment]
Siccome sono due progetti diversi, al momento no. A tal scopo invito a leggere integralmente il loro file README:

https://github.com/trinko/giuaschool#giuaschool

Riassumendo, prima bisogna installare Docker sul proprio computer locale. In Linux è facilissimo, in Windows abbastanza facile. Poi si copia-incolla una cartella sul sito vero e proprio.
