### ISSUE TITLE
Voti a giudizio invece che numerici (come da norma ministeriale)

### ISSUE THREAD

**Issue by sempliciniluigi89** [scaforchio/LAMPSchool#70]
Buonasera, sarebbe possibile per noi docenti di Religione mettere delle valutazioni giornaliere a giudizio invece che numeriche come richiesto dalla norma ministeriale?

Non mi riferisco alle valutazioni durante lo scrutinio, bensì alle valutazioni giornaliere e.g. interrogazione, verifica scritta etc.

Grazie!

**Comment by valerio-bozzolan** [comment]
Grazie per la segnalazione! Nei prossimi giorni è possibile che un volontario valuterà la richiesta senza tempi certi.

Se si ha fretta per lo sviluppo si può pregare il proprio dirigente scolatico di acquistare assistenza commerciale. Più info:

https://github.com/scaforchio/LAMPSchool#assistenza-commerciale

Attendiamo. Grazie ancora

**Comment by vittodevit** [comment]
Quando inserisci il voto lascia il campo numerico vuoto, e inserisci solamente il giudizio.

**Comment by valerio-bozzolan** [comment]
Se fossero necessarie ulteriori domande basta chiedere di nuovo. Grazie Vittorio per la risposta!

**Comment by sempliciniluigi89** [comment]
@vittodevit Facendo così non risulta poi la media numerica che devo poi andare a vedere in sede di scrutinio prima di determinare il voto finale

**Comment by vittodevit** [comment]
> @vittodevit Facendo così non risulta poi la media numerica che devo poi andare a vedere in sede di scrutinio prima di determinare il voto finale

Purtroppo quella va calcolata a mano.
