### ISSUE TITLE
uscite anticipate e ritardi in dad

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#74]
volevo chiedervi se era possibile  inserire più ritardi e uscite anticipate perchè gli alunni in dad  entrano ed escono tante volte per esempio ce un ora di italiano a 1° ora e sono presenti e a 2° ora ce matematica e alcuni si assentano ma si possono inserire solo un ritardo e un uscita  . si può fare questa cosa?

**Comment by rodolfo024** [comment]
Si, inserendo le giornate di dad si possono inserire le assenze orarie direttamente dalla gestione della lezione (dove si mettono i voti) senza bisogno di inserire l’evento. Se attivata verrà poi richiesta la giustificazione delle assenze orarie.

**Comment by gmontalbano5ct** [comment]
La giustificazioni di ogni lezione?

**Comment by rodolfo024** [comment]
Si, se si attiva da admin la funzione giustifica ore lezione (non ricordo la dicitura esatta), ed avendo attivata la gestione della dad e inserite le giornate, il docente può inserire l’ora di assenza dalla schermata di inserimento dei voti e dell’argomento. Il sistema poi chiederà di giustificare l’assenza di quell’ora.

**Comment by gmontalbano5ct** [comment]
Ora controllo

**Comment by gmontalbano5ct** [comment]
Guardi non mi fa mettere le ore
![Uploading Screenshot_2021-11-11-20-28-12-937_com.android.chrome.jpg…]()

**Comment by rodolfo024** [comment]
Non fa aprire lo screenshot

**Comment by gmontalbano5ct** [comment]
Non riesco
![Screenshot_2021-11-11-20-28-12-937_com android chrome](https://user-images.githubusercontent.com/93207960/141357952-77846526-5983-4ed1-858d-f95ab7652b50.jpg)

**Comment by rodolfo024** [comment]
Controlli che dall'account vicepreside si stata inserita la giornata di dad per quella classe;
Controlli che da admin sia stata abilitata la gestione della dad e che "Richiesta giustificazione per assenze alle singole lezioni" sia su "yes" e che la gestione delle assenze in basso "tipogestassenzelezione" sia impostato su ibrido.

**Comment by gmontalbano5ct** [comment]
Ok provo a farlo

**Comment by gmontalbano5ct** [comment]
Ok funziona ma una domanda se io non metto la giornata in dad si calcola in automatico l assenza?

**Comment by rodolfo024** [comment]
In una giornata "in presenza" se la gestione delle assenze è impostata su ibrido, non essendo la giornata di dad, le assenze vengono calcolate in automatico e non modificabili dal docente (come in dad).

**Comment by gmontalbano5ct** [comment]
Ok grazie mille
