### ISSUE TITLE
Riepilogo lezioni genitore: supporto docenti di sostegno

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#75]
buongiorno il mio problema è che nella sezione docente della firma mi spunta sempre il nome di un docente perché non mi spunta in nome del docente che ha realmente firmato?

Percorso pagina:

```
http://miodominio/lezioni/riepargomgendata.php?gio=11&meseanno=11%20-%202021
```

**Comment by gmontalbano5ct** [comment]
scusate mi correggo il nome di un docente perché ho provato a cambiare il nome del coordinatore ma il problema è sempre con quel docente come posso fare?

**Comment by valerio-bozzolan** [comment]
Scusi non ho capito. Per favore integri i due commenti in uno solo, il primo. C'è il tasto modifica sul primo commento (vicino alla faccina). Grazie mille

**Comment by gmontalbano5ct** [comment]
Ok fatto

**Comment by gmontalbano5ct** [comment]
Scusate qualcuno mi sa rispondere?

**Comment by valerio-bozzolan** [comment]
Per aiutare altri volontari a riprodurre il problema posso chiedere come si arriva a quella pagina? Quali click e con quale utenza? Qual è il percorso che trova nella barra degli indirizzi per quella pagina? (e.g. `/qualcosa/qualcosaltro.php`) Grazie scusi se sembra una domanda banale.

**Comment by gmontalbano5ct** [comment]
Un attimo che le giro uno screenshot

**Comment by gmontalbano5ct** [comment]
http://miodominio/lezioni/riepargomgendata.php?gio=11&meseanno=11%20-%202021

**Comment by vittodevit** [comment]
Quella pagina l'ho scritta io, purtroppo per mancanza di tempo l'ho testata senza docenti di sostegno. Appena trovo il tempo vedo di fixare.

**Comment by gmontalbano5ct** [comment]
Scusi mi può fare sapere quando ha completato?

**Comment by valerio-bozzolan** [comment]
Riceverà la solita mail automatica quando sarà risolto.
