### ISSUE TITLE
Idea: Lampschool Pro

### ISSUE THREAD

**Issue by rodolfo024** [scaforchio/LAMPSchool#78]
Potrebbe essere un'idea quella di realizzare una versione "pro" del registro basata su quella gratuita dove sono apportate le modifiche più richieste _e più complesse da realizzare_ (es. compiti assegnati, voti che non fanno media, recuperi scrutinio, cambiare il nome ai periodi, ecc...) dove è richiesto un contributo economico da parte dell'utente interessato.

**Comment by valerio-bozzolan** [comment]
Capisco l'idea di fondo. Grazie per lo spazio per permettermi di condividere un annuncio a riguardo.

Detto ciò, LAMPSchool è stato progettato per essere un registro elettronico libero e rimanere come tale: la licenza GNU AGPL incoraggia ogni fornitore (le scuole) ed ogni utilizzatore (studenti e docenti) all'uso, lo studio, la modifica e la condivisione delle modifiche per qualsiasi scopo (anche commerciale) fintanto che non siano aggiunte altre restrizioni.

Lo scopo è quello di creare un circolo virtuoso in cui, quando una singola scuola investe nel registro, anche le altre ne traggono beneficio. Quando una scuola paga un fornitore con assistenza commerciale, anche le altre ne traggono beneficio.

Invito le società di sviluppo software a rilasciare LAMPSchool Pro, inteso come **contratto di assistenza commerciale** a LAMPSchool per aiutare la singola realtà negli aggiornamenti e concordando ore di sviluppo software o dando garanzie di continuità di servizio.

Maggiori informazioni:

https://github.com/scaforchio/LAMPSchool#readme
