### ISSUE TITLE
Portale genitore: mostrare docente e media generale

### ISSUE THREAD

**Issue by sempliciniluigi89** [scaforchio/LAMPSchool#79]
Buongiorno ,è possibile implementare queste due piccole cose evidenziate nell'allegato per il portale genitore ?

![Screenshot LAMPSchool portale genitore](https://user-images.githubusercontent.com/93823125/141381187-e5e210dc-bd18-4382-9c3b-d874ced45398.png)

**Comment by scaforchio** [comment]
Direi che non sono prioritarie.

**Comment by vittodevit** [comment]
> Direi che non sono prioritarie.

Si può aggiungere in wishlist.
