### ISSUE TITLE
Giustifica assenze inviabili da genitori/tutori

### ISSUE THREAD

**Issue by tommasiangelo01** [scaforchio/LAMPSchool#9]
BUONGIORNO,SAREBBE POSSIBILE FAR MODO CHE LE ASSENZE O COMUNQUE I RITARDI E LE USCITE VENGANO GIUSTIFICATE ONLINE NEL PORTALE LAMPSCHOOL DIRETTAMENTE DAL PROFILO GENITORE O TUTTORE DEGLI ALUNNI?GRAZIE MILLE

**Comment by vittodevit** [comment]
Prendi questo commento con le pinze, ma la funzione **DOVREBBE** già essere parzialmente implementata.

**Comment by vittodevit** [comment]
Continuando su #53.
@valerio-bozzolan o @scaforchio potete chiudere.

**Comment by scaforchio** [comment]
Per poter effettuare la giustifica online è necessario l'invio da parte del registro di un OTP sul cellulare del genitore, per fare questo è necessario avere un contratto per l'invio degli SMS con un fornitore... il software verifica e se non c'è un nome utente per l'invio degli SMS non abilita la funzione.
