### ISSUE TITLE
Problema Trimestri

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#95]
buona sera volevo chiedere un altra cosa ma i trimestri come li metto?

**Comment by gmontalbano5ct** [comment]
Qualcuno mi può rispondere gruppo grazie

**Comment by manuelbarberi** [comment]
ancora non sono presenti i trimestri in lampschool... stanno provvedendo ad inserirli. un registro open source che ti consiglio è giuaschool ; una rivisitazione di lampschool ma con molte più funzioni. Va installato su uno spazio web non altervista... al momento non va da lì . Se hai uno spazio hosting ti posso aiutare

**Comment by gmontalbano5ct** [comment]
ma ci sono dei spazi web gratuiti?

**Comment by valerio-bozzolan** [comment]
> ma ci sono dei spazi web gratuiti?

Tutti i registri elettronici (liberi o proprietari) dovrebbero essere su un servizio di hosting che dia delle garanzie. Alcuni costano pochi euro al mese. Alcuni fra i più famosi sono gli hosting PHP di Aruba ed OVH.

Spesso si parla di tre euro al mese.

* https://www.ovhcloud.com/it/web-hosting/

Queste scelte dovrebbe farle il tecnico della scuola. In assenza di un tecnico della scuola l'ideale sarebbe avere una consulenza esterna per la scuola.

**Comment by vittodevit** [comment]
Consiglio il dominio con email + VPS aruba. Soluzione più costosa, ma con backup configurabili e tanta flessibilità.

**Comment by gmontalbano5ct** [comment]
Ok grazie mille

**Comment by gmontalbano5ct** [comment]
Mi potete fare sapere quando saranno disponibili i trimestri? Grazie
