### ISSUE TITLE
problema utente esame di stato per la scuola superiore 

### ISSUE THREAD

**Issue by gmontalbano5ct** [scaforchio/LAMPSchool#98]
non riesco ad inserire nessuna materia nessuna commissione e nessun anagrafica degli alunni con istituto superiore se metto scuola media riesco ad inserire tutto ciò qualcuno mi sa aiutare?

**Comment by gmontalbano5ct** [comment]
scusate qualcuno mi sa rispondere?

**Comment by valerio-bozzolan** [comment]
Spero che qualcuno possa aiutarti... nel frattempo consiglio di modificare il commento in alto per aggiungere più dettagli possibili. Specifica se si tratta di due registri diversi, e cosa significa che non si riesce: magari modifica il commento e trascina uno screenshot. Grazie mille
